export const ADD_TO_CART = "ADD_TO_CART";

export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const CART_RESET = "CART_RESET";

export const FAVOURITE_TO_CART = " FAVOURITE_TO_CART";
export const FAVOURITE_REMOVE_CART_ITEM = "FAVOURITE_REMOVE_CART_ITEM";
export const FAVOURITE_RESET = "FAVOURITE_RESET";
export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";
